concurrency: "1"

name: "Deno CI/CD 🦖🚀"

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"

      - name: Test Deno
        run: deno test

      - name: Deno Lint
        run: deno lint

      - name: Deno Format Check
        run: deno fmt --check
